name: pathrag

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pathrag-api:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      WORKING_DIR: /app/data
      UPLOAD_DIR: /app/uploads
      LOG_LEVEL: ${LOG_LEVEL-info}
    volumes:
      - pathrag_data:/app/data
      - pathrag_uploads:/app/uploads
      - pathrag_state:/state

  web:
    build:
      context: .
      dockerfile: Dockerfile.ui
      args:
        REACT_APP_API_URL: /api
    image: pathrag-web:latest
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "${WEB_HOST_PORT-8088}:80"   # ← был "80:80"
    # при необходимости добавь labels для маршрутизации

volumes:
  pathrag_data:
  pathrag_uploads:
  pathrag_state: